### ISSUE TITLE
DPLA use cases, suggested by Lincoln

### ISSUE THREAD

**Issue by sckott** [ropensci/rdpla#3]
- use case: visualizing datasets in John Carter Brown library at Brown Univ.
- use case: search for all photos of churches and make visualization

**Comment by adelenelai** [comment]
@sckott happy to take on the other use case vignette (visualising Brown datasets). Brown doesn't seem to be a contributor to dpla though - which of their datasets did you have in mind?

**Comment by sckott** [comment]
> Brown doesn't seem to be a contributor to dpla though

Brown is just the name of the library and the university, so yes, not an author on this package or DPLA itself. 

This wasn't my idea, so not totally sure, but I think the idea was to visualize all the datasets or a subset in that collection
